Add ant

diff --git a/10/openjdk8/s2i/bin/assemble b/10/openjdk8/s2i/bin/assemble
--- a/10/openjdk8/s2i/bin/assemble
+++ b/10/openjdk8/s2i/bin/assemble
@@ -18,8 +18,13 @@ if [[ "$1" == "-h" ]]; then
 fi
 
 if [ ! -f /tmp/src/pom.xml ]; then
-  echo "FATAL - No pom.xml found"
+
+if [ ! -f /tmp/src/build.xml ]; then
+
+  echo "FATAL - No pom.xml found MAVEN"
+  echo "FATAL - No build.xml found ANT"
   exit 1
+fi
 fi
 
 
@@ -40,6 +45,7 @@ echo "VARIABLE TAG_VERSION ENCONTRADA USANDO: $TAG_VERSION"
 echo $TAG_VERSION > /opt/version
 fi
 
+if [ -f /opt/src/pom.xml ]; then
 
 if [ -z "$NEXUS_MIRROR_URL" ]; then
 echo "NO NEXUS_MIRROR_URL ENCONTRADO"
@@ -94,15 +100,35 @@ exit $ERR
 
 fi
 
+fi
+
+if [ -f /opt/src/build.xml ]; then
+echo "COMPILANDO ANT.."
+cd /opt/src && ant build
+
+ERR=$?
+    if [ $ERR -ne 0 ]; then
+echo "LA COMPILACION SALIO CON CODIGO DE ERROR $ERR"
+exit $ERR
+fi
+fi
+
+
 echo "---> COPIANDO APLICACION GENERADA AL DIRECTORIO DE DEPLOY..."
-cd /opt/src && find . -name '*.war' | xargs cp -t /opt/wildfly/standalone/deployments || find . -name '*.ear' | xargs cp -t /opt/wildfly/standalone/deployments && echo "APP INSTALADA!"
+find /opt/src -name '*.war' | xargs cp -t /opt/wildfly/standalone/deployments
+find /opt/src -name '*.ear' | xargs cp -t /opt/wildfly/standalone/deployments
+echo "APP INSTALADA!" 
 
 war=`ls -1 /opt/wildfly/standalone/deployments/*.war 2>/dev/null | wc -l`
 ear=`ls -1 /opt/wildfly/standalone/deployments/*.ear 2>/dev/null | wc -l`
 
+echo "EAR ENCONTRADO $ear"
+echo "WAR ENCONTRADO $war"
+
 if [ $war != 0 ] && [ $ear != 0 ]; then
+echo "ELIMINANDO WAR, MANTENIENDO EAR"
 rm -rf /opt/wildfly/standalone/deployments/*.war
 fi
 
 ls -1 /opt/wildfly/standalone/deployments/
-cd $HOME && rm -rf /opt/src
+cd $HOME && rm -rf /opt/src /tmp/src
